server.address=0.0.0.0

# Expose the prometheus and health endpoints over HTTP
management.endpoints.web.exposure.include=health,info,prometheus
management.metrics.export.prometheus.enabled=true

#Clean up metric names by converting camelCase to dots (recommended)
management.metrics.use-global-registry=true

llm.server.rest.base_url=http://127.0.0.1:8000/v1/generate
llm.server.grpc.port=50051
llm.server.grpc.host=127.0.0.1